djangocalendar/cal/urls.py
# cal/urls.py

from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^workout/new/$', views.event, name='workout_new'),
    url(r'^workout/edit/(?P<workout_id>\d+)/$', views.event, name='workout_edit'),
    url(r'^video/new/$', views.video, name='video_new'),
    url(r'^video/edit/(?P<video_id>\d+)/$', views.video, name='video_edit'),
    url(r"video/(?P<pk>\d+)/$", views.VideoPDetailView.as_view(), name="video_detail"),
    url(r"video/$", views.VideoPListView.as_view(), name="video_list"),
    url(r'^video/tagged/(?P<slug>[-\w]+)/$', views.TagListView.as_view(), name="tagged_videos"),
]

djangocalendar/djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
    #path('video/', include('cal.urls'),name="videos"),
]

djangocalendar/cal/models.py
# cal/models.py

from django.db import models
from django.urls import reverse

# for YouTube
from embed_video.fields import EmbedVideoField
#for tags
from taggit.managers import TaggableManager
TAGGIT_CASE_INSENSITIVE = True

class Video(models.Model):
    title = models.CharField(max_length=200)
    #link = models.URLField(blank=True)
    video = EmbedVideoField(verbose_name="Video", help_text="Please enter video URL", blank=True)
    channel = models.CharField(max_length=50)
    tags = TaggableManager(blank=True)
    
    class Meta:
        ordering = ['id']

    def __str__(self):
        return ' - '.join([self.channel, self.title])

    def get_colored_name(self):
         return color_words(self.__str__())

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("cal:video_detail", kwargs={"pk": self.pk})

class Workout(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField()
    date = models.DateField()
    duration = models.IntegerField(default=-99)
    bpm = models.IntegerField(default=-99)
    calories = models.IntegerField(default=-99)
    
    class Meta:
        ordering = ['date']

    @property
    def get_html_url(self):
        url = reverse('cal:workout_edit', args=(self.id,))
        if self.video:
            return f'<a href="{url}"> {self.video.get_colored_name()} </a>'
        else:
            n = self.description.find('\n')
            if n == -1:
               string = color_words(self.description)
            else:
               string = color_words(self.description[:n])
            return f'<a href="{url}"> {string} </a>'

    def __str__(self):
        return self.description

def color_words(string):
   red = '#d11569'
   green = '#3a9278'
   yellow = '#f9c74f'
   blue = '#4f5bd5'
   light_green = '#00b300'
   purple = '#962fbf'
   light_blue = '#0099ff'
   dictionary={'abs':red, 'ab':red, 'abdomen':red, 'core':red, 'gutts':red, 'plank':red,
               'total':green, 'hiit':green, 'full':green,
               'knee':yellow, 'posture':yellow, 'rehab':yellow, 'fix':yellow, 'pain':yellow,
               'booty':blue, 'legs':blue, 'leg':blue, 'thigh':blue, 'butt':blue, 'butts':blue,
               'arms':light_green, 'upper':light_green, 'shoulders':light_green, 'chest':light_green, 'back':light_green, 'arm':light_green,
               'cardio':purple,
               'stretch':light_blue, 'stretching':light_blue, 'stretches':light_blue, 'flexibility':light_blue}
   words = string.split(" ")
   for i in range(0, len(words)):
      word = words[i]
      if word.lower() in dictionary.keys():
         words[i] = f'<span style="color: {dictionary[word.lower()]}; font-weight:bold"> {word} </span>'
   string=" ".join(words)
   return string

djangocalendar/cal/forms.py
# cal/forms.py

from django.forms import ModelForm, DateInput
from cal.models import Workout, Video
from datetime import datetime   

class EventForm(ModelForm):
  class Meta:
    model = Workout
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'date': DateInput(attrs={'type': 'date', 'value': datetime.now().strftime("%Y-%m-%d")}, format='%Y-%m-%d'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['date'].input_formats = ('%Y-%m-%d',)

class VideoForm(ModelForm):
  class Meta:
    model = Video
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(VideoForm, self).__init__(*args, **kwargs)

djangocalendar/cal/views.py
# cal/views.py

from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.shortcuts import redirect
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm, VideoForm

def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    model = Workout
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)

        # we calculate the previous and next month’s date in cal/views.py and pass it as template variables to our cal/calendar.html
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def event(request, workout_id=None):
    instance = Workout()
    if workout_id:
        instance = get_object_or_404(Workout, pk=workout_id)
    else:
        instance = Workout()
    
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/workout.html', {'form': form})

def video(request, video_id=None):
    instance = Video()
    if video_id:
        instance = get_object_or_404(Video, pk=video_id)
    else:
        instance = Video()
    
    form = VideoForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        if video_id==None:
            # goes to the video_list page, because there is no ID
            return HttpResponseRedirect(reverse('cal:video_list'))
        else:
            # goes to the video_detail page of the video just edited
            return redirect('cal:video_detail', pk=video_id)
    return render(request, 'cal/video.html', {'form': form})

class VideoPListView(generic.ListView):
    model = Video
    paginate_by = 50


class VideoPDetailView(generic.DetailView):
    model = Video

class TagListView(generic.ListView):
    """The listing for tagged books."""
    template_name = "cal/video_list.html"

    def get_queryset(self):
        return Video.objects.filter(tags__slug=self.kwargs.get("slug")).all()

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        context["tag"] = self.kwargs.get("slug")
        return context

djangocalendar/cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>Workout Calendar</title>
<link rel="shortcut icon" type="image/png" href="{% static 'images/WoCal4.png' %}"/>
</head>
<body>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

djangocalendar/cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
Workout Calendar
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'cal:workout_new' %}"> New Workout </a>
	<a class="btn btn-info left" href="{% url 'cal:video_list' %}"> Videos </a>
</div>

{{ calendar }}
{% endblock %}

djangocalendar/cal/templates/cal/video.html
<!-- cal/templates/cal/event.html -->

{% extends 'cal/base.html' %}

{% block title %}
   Video
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:video_list' %}"> Back to list </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

djangocalendar/cal/templates/cal/video_detail.html
{% extends "cal/base.html" %}

{% load embed_video_tags %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:video_list' %}"> Back to list </a>
	<a class="btn btn-info right" href="{% url 'cal:workout_new' %}"> New Workout </a>
	<a class="btn btn-info right" href="{% url 'cal:video_edit' object.pk %}"> Edit Video </a>
</div>
{% video object.video as my_video %}
  <pre>
    Tags: {% for tag in object.tags.all %}<a href="{% url 'cal:tagged_videos' tag.slug %}">{{ tag }}</a>, {% endfor %}
    URL: {{ my_video.url }}
    {#  Tags: {{my_video.tags.all|join:", "}} Backend: {{ my_video.backend }} Code: {{ my_video.code }} Thumbnail: {{ my_video.thumbnail }} HTTPS: {% if my_video.protocol == 'https' %}Yes{% else %}No{% endif %} #}
  </pre>
  {% video my_video '1280x720' %}
{% endvideo %}

{% endblock %}

djangocalendar/cal/templates/cal/video_list.html
{% extends "cal/base.html" %}

{% load embed_video_tags %}

{% block title %}
   Videos
{% endblock %}

{% block content %}
<div class="clearfix">
   <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
	<a class="btn btn-info right" href="{% url 'cal:video_new' %}"> New Video </a>
</div>

{% if tag %}
    <h4>Videos tagged as {{ tag }}</h4>
{% endif %}

  <table class="table">
    {% for post in object_list %}
    <tr>
      {% video post.video as video %}
      <td><img src="{{ video.thumbnail }}" width=60 height=45 class="img-rounded"></td>
        <td><a href="{{ post.get_absolute_url }}">{{ post.channel }} - {{ post.title }}</a>
         {% if post.tags.all %} - <small>Tags: {% for tag in post.tags.all %}<a href="{% url 'cal:tagged_videos' tag.slug %}">{{ tag }}</a> {% endfor %} {% endif %}</small></td>
      {% endvideo %}
    </tr>
    {% endfor %}
  </table>

  <ul class="pager">
    {% if page_obj.has_previous %}
    <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Older</a></li>
    {% endif %}
    {% if page_obj.has_next %}
      <li class="next"><a href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a></li>
    {% endif %}
  </ul>
{% endblock %}

djangocalendar/cal/templates/cal/video_plus_detail.html
{% extends "cal/base.html" %}

{% load embed_video_tags %}

{% block title %}
{{ object.title }}
{% endblock %}


{% block content %}
<div class="clearfix">
	<a class="btn btn-info right" href="{% url 'cal:video_list' %}"> Back to list </a>
</div>

{% video object.video as my_video %}
  <pre>
    <!-- Backend: {{ my_video.backend }} -->
    URL: {{ my_video.url }}
    <!-- Code: {{ my_video.code }}
    Thumbnail: {{ my_video.thumbnail }}
    HTTPS: {% if my_video.protocol == 'https' %}Yes{% else %}No{% endif %}</pre> -->

  {% video my_video "large" %}
{% endvideo %}

{% endblock %}

djangocalendar/cal/templates/cal/video_plus_list.html
{% extends "cal/base.html" %}

{% load embed_video_tags %}

{% block title %}
Videos
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info right" href="{% url 'cal:video_new' %}"> New Video </a>
</div>


  <table class="table">
    {% for post in object_list %}
    <tr>
      {% video post.video as video %}
      <td><img src="{{ video.thumbnail }}" width=60 height=45 class="img-rounded"></td>
        <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
      {% endvideo %}
    </tr>
    {% endfor %}
  </table>

  <ul class="pager">
    {% if page_obj.has_previous %}
    <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">&larr; Older</a></li>
    {% endif %}
    {% if page_obj.has_next %}
      <li class="next"><a href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a></li>
    {% endif %}
  </ul>
{% endblock %}

djangocalendar/cal/templates/cal/workout.html
<!-- cal/templates/cal/event.html -->

{% extends 'cal/base.html' %}

{% block title %}
Workout
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}